FROM almalinux:9
CMD [ "google.com" ] #this can be override by passing a different command when running the container
ENTRYPOINT [ "ping"  ] this can't be ovveride by passing a different command when running the container, it will always ping google.com for 4 times.